//tags
export const tagsArray = [
    "Life",
    "Startup",
    "Blockchain",
    "Poetry",
    "Life Lessons",
    "Politics",
    "Health",
    "Love",
    "Travel",
    "Technology",
    "Entrepreneurship", 
    "Self Improvement",
    "Education",
    "Writing",
    "Business",
    "Cryptocurrency",
    "Design",
    "Social Media",
    "Music",
    "Relationships",
    "Religion",
    "Social Media",
    "Sports",
    "Mental Health",
    "Productivity",
    "Programming",
    "Food",
    "Leadership",
    "Javascript",
    "Art",
    "Fiction",
    "Humor",
    "Artificial Intelligence",
    "UX",
    "Culture",
    "Books",
    "Photography",
    "Creativity",
    "Data Science",
    "Psychology",
    "Software Development",
    "Coronavirus",
    "Self",
    "Family"
  ];