import Link from "next/link";
import "../styles/globals.css";

export const metadata = {
  title: "Andy's Blog",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <div>
      <Link href={"/"}>
        <h1 className="">Andy's Blog</h1>
      </Link>
      <h2>Welcome to my blog.</h2>
    </div>
  );

  const footer = (
    <div>
      <h1>Developed by Andy</h1>
    </div>
  );

  return (
    <html lang="en">
      <body className="px-10  lg:bg-blue-900">
        <section className="min-h-screen md:flex w-auto mt-6 relative">
          {/* {header} */}

          <div className=" flex justify-center w-full">
            <div className=" flex justify-around  mt-1 ">
              <h2 className="w-24 text-gray-400 hover:text-gray-500 hover:bg-gradient-to-b from-white to-gray-100   font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
                Posts
              </h2>
              <h2 className="w-28 text-gray-400 hover:text-gray-500 hover:bg-gradient-to-b from-white to-gray-100   font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
                About me
              </h2>
              <h2 className="w-24 text-gray-400 hover:text-gray-500 hover:bg-gradient-to-b from-white to-gray-100   font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
                Contact
              </h2>
            </div>
          </div>

          <div className=" mt-3 p-3 flex-row w-full justify-center">
            {children}
          </div>

          {/* {footer} */}
        </section>
      </body>
    </html>
  );
}
